config/routes.rb
Rails.application.routes.draw do
  get 'admin/createPeakHours'
  get 'admin/editPeakHours'
  # home page
  root to: 'home#index'

  # browse listings of sports_centers and their courts
  resources :users, only: [:new, :create, :show] do
  end

  get '/demo', to: 'home#demo', as: "home_demo"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :sports_centres, only: [:new, :create, :index] do
  end

  get "/sports_centres/:id/check_availability", to: "sports_centres#check_availability", as: "sports_centre_check_availability"
  # move to new admin controller later
  get "/sports_centres/:id/user_show", to: "sports_centres#user_show", as: "sports_centre_user"

  get "/sports_centres/:sports_centre_id/booking_success", to: "sports_centres#booking_success", as: "sports_centre_booking_success"
  get "/sports_centres/:id/booking_failure", to: "sports_centres#booking_failure", as: "sports_centre_booking_failure"
  get "/sports_centres/:id/booking_cancelled", to: "sports_centres#booking_cancelled", as: "sports_centre_booking_cancelled"
  # above route overlaps with the one below, should try to simplify routes later on
  get "/sports_centres/:id/:date", to: "sports_centres#user_show", as: "sports_centre_user_date"

  # after a transaction successfully completes


  #scope :admin, as: 'admin' do
  #  resources :sports_centres, only: [:show] do
  #  end
  #end

  get "admin/sports_centre/:id", to: "admin#show", as: "admin_sports_centre"

  get "admin/sports_centre/:id/newPeakHour", to: "admin#newPeakHour", as: "new_peak_hour"

  get 'admin/sports_centre/:id/date', to: "admin#show_again", as: 'admin_show_again'
  get 'admin/sports_centre/:id/payMoneyOwed', to: "admin#pay_money_owed", as: 'admin_pay_money_owed'
  get "admin/sports_centres/:id/getPastRecords", to: "admin#getPastRecords", as: "admin_get_past_records"
  get "admin/sports_centre/:id/payment_success", to: "admin#payment_success", as: "admin_payment_success"

  post "admin/sports_centre/:id/lockPage", to: "admin#lockPage", as: "admin_lock_page"
  post "admin/sports_centre/:id/checkAdminPin", to: "admin#check_admin_pin", as: "admin_check_admin_pin"
  post "admin/sports_centre/:id/addNewBookings", to: "admin#addNewBookings", as: "admin_add_new_bookings"
  post "admin/sports_centre/:id/deleteBooking", to: "admin#deleteBooking", as: "admin_delete_booking"
  post "admin/sports_centre/:id/deleteOrder", to: "admin#deleteOrder", as: "admin_delete_order"

  post "admin/sports_centres/:id/peak_hours", to: "admin#updatePeakHours", as: "admin_update_peak"

  post "admin/sports_centres/:id/update_logo", to: "admin#update_logo", as: "admin_update_logo"
  post "admin/sports_centres/:id/update_hours", to: "admin#update_hours", as: "admin_update_hours"
  post "admin/sports_centres/:id/update_prices", to: "admin#update_prices", as: "admin_update_prices"
  post "admin/sports_centres/:id/update_plan", to: "admin#update_plan", as: "admin_update_plan"

  post "admin/sports_centres/:id/check_pin", to: "admin#check_pin", as: "admin_check_pin"
  # api versioning
  namespace :api do
    namespace :v1, defaults: {format: 'json'} do
        resources :sports_centres, only: [:show] do
          get "confirm_email", on: :member
          post "payment_nudge", on: :member
          resource :bookings, shallow: true, only: [:create] do
            post "initiate", on: :collection
            post "claim_booking", on: :collection
            get "check_availability", on: :collection
            post "check_qrCode", on: :collection
          end
        end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :sports_centre, optional: true
  belongs_to :representative, optional: true
  enum state: { 'NSW':0, 'VIC':1, 'QLD':2, 'ACT':3, 'SA':4, 'WA':5, 'NT':6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :sports_centre
  belongs_to :order
  belongs_to :user, optional: true
  enum bookingType: { 'casual':0, 'regular':1 }
  enum courtType: { 'halfCourt':1, 'fullCourt':2 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :sports_centre, optional: true
  enum relationship: { 'owner':0, 'executive':1 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :bookings, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :sports_centre
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :booking
  belongs_to :facility
end

app/models/representative.rb
class Representative < ApplicationRecord
  has_secure_password
  belongs_to :sports_centre, optional: true
  #validates :email, presence: true, uniqueness: true
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
end

app/models/sports_centre.rb
class SportsCentre < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  serialize :prices, Hash
  serialize :opening_hours, Hash
  serialize :peak_hours, Hash
  #serialize :activities, Hash

  has_one :address, dependent: :destroy
  has_one :representative, dependent: :destroy
  validates_presence_of :address
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :representative
  has_many :bookings, dependent: :destroy
  has_one_attached :logo

  has_many :contacts, dependent: :destroy
  has_many :payments
  accepts_nested_attributes_for :contacts
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # console
  end

  def about
  end

  def demo
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/check_admin_pin.js.erb
var buttonLock = document.querySelector("<%= @buttonId %> i.lock");
var panel = buttonLock.parentElement.parentElement.getAttribute("data-connectedRow");

<% if @isAdmin %>
  // remove lock screens
    var lockScreen = document.querySelector(`${panel} div.overlay`);
    lockScreen.classList.add("d-none");
  // remove lock icons
    var buttonLock = document.querySelector("<%= @buttonId %> i.lock");
    buttonLock.classList.add("d-none");
<% else %>
    //console.log(panel);
    document.querySelector(`${panel} .overlay input`).classList.add("is-invalid");
<% end %>

app/views/admin/check_pin.js.erb
var pin_input = document.querySelector("#sports_centre_booking_pin");
var hiddenButton = document.querySelector("#pinNameHolder");

<% if @booking_found %>
  var bookingId = <%= @matchingBooking_id %>;
  // add is-valid to input
  // locate the booking on the grid
  // add border to the matching booking's name
  pin_input.classList.add("is-valid");
  hiddenButton.setAttribute("data-booking-id", bookingId);
  hiddenButton.click();
<% else %>
   pin_input.classList.add("is-invalid");
  // add is-invalid to input
<% end %>

app/views/admin/createPeakHours.html.erb
<h1>Admin#createPeakHours</h1>
<p>Find me in app/views/admin/createPeakHours.html.erb</p>

app/views/admin/editPeakHours.html.erb
<h1>Admin#editPeakHours</h1>
<p>Find me in app/views/admin/editPeakHours.html.erb</p>

app/views/admin/getPastRecords.js.erb
var recordHolder = document.querySelector("#paymentRecordHolder");
recordHolder.innerHTML = "";
var templateRow = document.querySelector("#payFeesBody .templateRecordRow");
var cloneRecordRow;
var children;
<% @arrayDailyTransactions.each do |transaction| %>
  cloneRecordRow = templateRow.cloneNode(true);
  children = cloneRecordRow.children
  children[0].innerHTML = "<%= transaction["EndDateTime"].split("T")[1][0,5] %>";
  children[1].innerHTML = "<%= "#{transaction["MerchantData"]["booking"]["courtType"].sub("Court", "-court")}" +
                          " #{transaction["MerchantData"]["booking"]["bookingType"]}" +
                          " #{transaction["MerchantData"]["booking"]["activityType"]}" %>";
  children[2].innerHTML = "<%= "#{transaction["MerchantData"]["booking"]["startTime"]}- #{transaction["MerchantData"]["booking"]["endTime"]}" %>"
  children[3].firstElementChild.setAttribute("title", "<%= transaction["MerchantData"]["order"]["firstDayBookings"] + transaction["MerchantData"]["order"]["allDates"] %>");
  children[3].firstElementChild.innerHTML = "<%= transaction["MerchantData"]["order"]["allDates"].count + 1 %>";
  children[4].innerHTML = "<%= transaction["TransactionRefNo"] %>";
  children[5].innerHTML = "$<%= '%.2f' % transaction["AmountPaid"] %>";
  children[6].innerHTML = <% if (transaction["MerchantData"]["order"]["totalCommission"]).present? %>
    "$<%=  '%.2f' % (transaction["MerchantData"]["order"]["totalCommission"])%>"
  <% else %>
    "<%= 'N/A' %>"
  <% end %>;
  recordHolder.appendChild(cloneRecordRow);
  cloneRecordRow.classList.remove("d-none");
<% end %>

app/views/admin/payment_success.html.erb
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-8">
      <%= image_tag((url_for asset_path("weballText.png")), class: "mx-auto d-block image-contain logo-height") %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-10 mt-5">
      <h2 class="text-center">Thank you for partnering with WeBall.</h2>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-3">
      <%= image_tag("email-sent-icon.png", class: "mx-auto d-block img-fluid") %>
    </div>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-6">
      <h4 class="text-center">A payment invoice will be sent to <span class="text-primary"><%= @sportsCentre.email %></span> shortly.</<h4>
    </div>
  </div>
  <div class="row justify-content-center mt-4">
    <div class="col-6">
      <h4 class="text-center"><%= link_to "Return to your admin dashboard.", admin_sports_centre_path(@sportsCentre), class: "btn btn-lg btn-primary text-white" %></<h4>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="text-right"><small class="text-muted">Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></p>
    </div>
  </div>
</div>

app/views/admin/show_again.js.erb
// if the session of bookin exist?
<% if session[:bookings] %>
var bookings = <%= raw session[:bookings] %>;

// newly selected date value
var newDate = document.querySelector('#my_hidden_input').value;
var arr = newDate.split('/');
var formattedDate = `${arr[2]}-${arr[0]}-${arr[1]}`
//console.log(formattedDate);
// reverse format
var i = 0;
var j = 0;
var booking_start;
var booking_end;
var columnArray;
var nextColumnArray;
var booked = false;
var columnNumber;
var booking;
var table = document.querySelector('table.table-sm');
clearTable(table);

var firstId = document.querySelector("#dashBoardTable td");
firstId.classList.add("border-darkBlue");
console.log("border added!");
//alert("heck!");

while (i < bookings.length) {
  //console.log("fd", formattedDate);
  //console.log("bd", bookings[i].date);
  if (bookings[i].date === formattedDate) {
    booking = bookings[i];
    //console.log(booking);
    j = 0;
    booking_start = booking.startTime.substr(11,5);
    booking_end = booking.endTime.substr(11,5);
    console.log("start", booking_start);
    console.log("end", booking_end);
    columnArray = document.querySelectorAll(`[data-court="${booking.court_no}"]`);
    var counter = 0;
    if (booking.courtType == "halfCourt") {
          console.log(booking.courtType);
          while (j < columnArray.length) {
            if (columnArray[j].dataset.time == booking_start) {
              booked = true;
            }
            if (columnArray[j].dataset.time == booking_end) {
              booked = false;
            }
            if (booked) {
              columnArray[j].classList.add(`table${booking.sportsType}`, "booked");
              columnArray[j].setAttribute("data-booking-id", `${booking.id}`);
              columnArray[j].setAttribute("data-toggle", "tooltip");
              columnArray[j].setAttribute("title", `${booking.name}\nType: ${booking.sportsType}\nStart:`
              + ` ${convertToAMPM(booking_start)}\nEnd: ${convertToAMPM(booking_end)}`);
              //columnArray[j].setAttribute("data-placement", "top");
              if (counter == 0) {  // first selected td.
                  columnArray[j].innerHTML = `<div>${booking.name}</div>` + "<div class='delete-booking'" + `data-booking-id=${booking.id} data-order-id=${booking.order_id}>&times</div>`
                  columnArray[j].classList.add("textHolder");
                  counter++;
              }
            }
            j++;
          }
     } else if (booking.courtType == "fullCourt") {
          console.log(booking.courtType)
         nextColumnArray = document.querySelectorAll(`[data-court="${booking.court_no + 1}"]`);
         while (j < columnArray.length) {
           if (columnArray[j].dataset.time == booking_start) {
             booked = true;
           }
           if (columnArray[j].dataset.time == booking_end) {
             booked = false;
           }
           if (booked) {
             columnArray[j].classList.add(`table${booking.sportsType}`, "booked");
             columnArray[j].setAttribute("data-booking-id", `${booking.id}`);
             columnArray[j].setAttribute("data-toggle", "tooltip");
             columnArray[j].setAttribute("title", `${booking.name}\nType: ${booking.sportsType}\nStart:`
             + ` ${convertToAMPM(booking_start)}\nEnd: ${convertToAMPM(booking_end)}`);
             nextColumnArray[j].classList.add(`table${booking.sportsType}`, "booked");
             nextColumnArray[j].setAttribute("data-booking-id", `${booking.id}`);
             nextColumnArray[j].setAttribute("data-toggle", "tooltip");
             nextColumnArray[j].setAttribute("title", `${booking.name}\nType: ${booking.sportsType}\nStart:`
             + ` ${convertToAMPM(booking_start)}\nEnd: ${convertToAMPM(booking_end)}`);
             if (counter == 0) {  // first selected td.
                 columnArray[j].innerHTML = `<div>${booking.name}</div>`;
                 columnArray[j].classList.add("textHolder");
                 nextColumnArray[j].innerHTML = "<div></div><div class='delete-booking'" + `data-booking-id=${booking.id} data-order-id=${booking.order_id}>&times</div>`;
                 nextColumnArray[j].classList.add("textHolder");
                 counter++;
             }
           }
           j++;
         }
     }
  }
  i++;
}
<% end %>
//var bookings = JSON.parse(bookings_json);

function clearTable(table) {
  var bookedTimes = table.querySelectorAll('td.booked');
  var textHolders = table.querySelectorAll('td.textHolder');
  var i = 0;
  var j = 0;
  while (i < bookedTimes.length) {
    bookedTimes[i].setAttribute("class", "td-flex d-flex justify-content-between");
    i++;
  }
  while (j < textHolders.length) {
    textHolders[j].innerHTML = "";
    j++;
  }
}

/*
var bookedFullTimes = table.querySelectorAll('td[class^="table"]');
var j = 0;
while (j < bookedFullTimes.length) {
  bookedFullTimes[j].classList.remove('td[class^="table"]');
  j++;
} */

function convertToAMPM(timeString) {
  var hours_and_minutes = timeString.split(":");
  var parsed_int = parseInt(hours_and_minutes[0]);
  var int = (parsed_int % 12 == 0) ? 12 : parsed_int % 12;
  var am_or_pm = (hours_and_minutes[0] >= 12) ? "PM" : "AM";
  return `${int}:${hours_and_minutes[1]}${am_or_pm}`
}

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
  <nav class="pl-md-0 navbar navbar-light navbar-expand-lg shadow-sm bg-white m-0"><%= link_to image_tag(asset_path("orangeWeballLogo.png"), class: "max-text-logo"), root_path, class: "navbar-brand" %>
      <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler collapsed">
        <span class="navbar-toggler-icon"></span></button>
        <div id="navbarSupportedContent" class="collapse navbar-collapse pr-0">
          <ul class="navbar-nav ml-auto float-none justify-content-end">
              <li class="nav-item nav-grey d-none"><%= link_to '(Browse Sports Centres)', sports_centres_path, class: "nav-link" %></li>
              <% if logged_out? %>
                <li class="nav-item nav-grey"><%= link_to 'Demo', home_demo_path, class: "nav-link" %></li>
                <li class="nav-item nav-grey"><%= link_to 'Log In', login_path, class: "nav-link" %></li>
                <li class="nav-item mr-md-2 nav-grey"><%= link_to 'Register', new_sports_centre_path, id: "register", class: "nav-link"%></li>
             <% else %>
              <li class="dropdown d-flex">
                <button class="btn nav-link dropdown-toggle" type="button" data-toggle="dropdown">
                  <% if @sports_centre %>
                  <i class="fa fa-user-circle mr-md-2"></i><span class="sports_centre_holder" id="id-holder" data-sports-centre-id=<%= @sports_centre.id %>
                      data-number-of-courts=<%= @sports_centre.numberOfCourts %>><%= @sports_centre.title %></span>
                  <span class"caret"></span>
                  <% end %>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                  <div class="row mx-0 my-3">
                    <%= image_tag("cameraIcon.png", size: "72x72", class: "col-4") %>
                    <div class="col-8 pl-0">
                      <div class="row align-self-center mx-0">
                        <h5 class="col font-weight-bold px-0 mb-0 dropdown-margin-top" href="#">
                          <%= current_user.email if logged_in_as_user? %>
                          <%= current_sports_centre.title if logged_in_as_sports_centre? %>
                        </h5>
                      </div>
                      <div class="row align-self-bottom mx-0">
                        <a class="col px-0" href="#">
                          Add a profile picture
                        </a>
                      </div>
                    </div>
                  </div>
                  <div class="dropdown-divider row"></div>
                  <div class="row mx-0 dropdown-item">
                    <%= link_to "Manage Bookings", admin_sports_centre_path(current_sports_centre), class: "dropdown-item" if logged_in_as_sports_centre? %>
                  </div>
                  <div class="row mx-0 dropdown-item">
                    <a class="dropdown-item" href="#">Messages</a>
                  </div>
                  <div class="row mx-0 dropdown-item">
                    <%= link_to "Sign out", logout_path, method: "delete", class: "dropdown-item" %>
                  </div>
                </div>
              </li>
              <% end %>
          </ul>
        </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookACourt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
    integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
    crossorigin=""/>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>
    <link href="https://unpkg.com/leaflet-geosearch@latest/assets/css/leaflet.css" rel="stylesheet" />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
     integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
     crossorigin=""></script>
     <!-- loading the widget video -->
     <script src="https://fast.wistia.com/embed/medias/by9e2m5uzk.jsonp" async></script>
     <script src="https://fast.wistia.com/assets/external/E-v1.js" async></script>
     <!-- allow stripe elements integration -->
     <script src="https://unpkg.com/leaflet-geosearch@latest/dist/bundle.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyAZKKyF8A71mmTOstHUgz4KHErK799gm1o"></script>
    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/b7ac405f9f.js" crossorigin="anonymous"></script>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/notifications_mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_pack_tag "mailer", media: "all" %>
  </head>
  <body class="bg-light">
    <%= yield %>
  </body>
</html>